using System.Collections.Generic;
using WordsWithBrutes.Model;

namespace WordsWithBrutes.Components
{
    /// <summary>
    /// Responsible for determining which words were generated by a given play as well as the potential points for this play
    /// </summary>
    public interface IDetermineTheTotalPointsAndWordsCreatedByAPlay
    {
        /// <summary>
        /// Gets all the word(s) formed by the given play as well as the points earned for those word(s)
        /// </summary>
        WordsPlayedAndPointsScored GetPlayedWordsAndTotalPoints(GameState gameState, IEnumerable<PlayedTile> playedTiles);
    }
}
