using System.Collections.Generic;
using WordsWithBrutes.Model;

namespace WordsWithBrutes.Components
{
    /// <summary>
    /// Responsible for determining which words were generated by a given play
    /// </summary>
    public interface IDetermineTheWordsCreatedByAPlay
    {
        IEnumerable<string> GetPlayedWords(Challenge challenge, IEnumerable<PlayedTile> playedTiles);
    }
}
